version: '3'
services:
  mysql:
    image: mariadb
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: books
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql

  books-api:
    build: backend
    restart: always
    environment:
      TZ: Europe/UTC
    ports:
      - 8080:8080
    depends_on:
      - mysql
    image: books-api
    container_name: books-api

volumes:
   mysql:
